Handle mismatched quotes and smart quotes
openstax/open-search pull request #115
Opened 2023-09-26 20:48 UTC by Dantemss

For: https://github.com/openstax/unified/issues/2613

- Handle smart quotes by converting them to normal quotes before searching
- Handle mismatched quotes by closing them

2023-09-28 19:13 UTC, TomWoodward requested changes
why is it necessary to close the mismatched quotes? i feel like this is going to lead to unexpected behavior if you just happen to have a quote in your search term (like maybe you copy pasted half a quote out of the content or something). would it be better to ignore mismatched quotes? what does it do now?

2023-09-28 20:17 UTC, Dantemss commented
What it does now is that mismatched quotes disable the fuzzy search, but they are not treated as phrases by OpenSearch so the words can be in any order. If you want I can do a gsub or something to remove the quotes completely so they are treated like unquoted words, or I can leave them as this kind of in-between behavior if you think it would be useful.

2023-09-29 20:48 UTC, TomWoodward commented
i'm not sure i'm totally understanding, but i would think that a mismatched quote should essentially be ignored

2023-10-04 19:51 UTC, Dantemss commented
Changed pattern so mismatched quotes are ignored:

```
irb(main):002:0> 'the quick brown fox'.scan(/[^\s"—–-]+|"[^"]*"/)
=> ["the", "quick", "brown", "fox"]
irb(main):003:0> 'the quick "brown fox'.scan(/[^\s"—–-]+|"[^"]*"/)
=> ["the", "quick", "brown", "fox"]
irb(main):004:0> 'the quick "brown fox"'.scan(/[^\s"—–-]+|"[^"]*"/)
=> ["the", "quick", "\"brown fox\""]
irb(main):005:0> 'the quick"brown fox'.scan(/[^\s"—–-]+|"[^"]*"/)
=> ["the", "quick", "brown", "fox"]
```

2023-10-04 20:27 UTC, TomWoodward approved these changes

2023-10-05 15:30 UTC, merged